const data = {
  products: [
    {
      _id: '1',
      name: 'Forest Green Dad Hat',
      category: 'dad hats',
      image1: '../images/PSAVOGRN19.jpg',
      image2: '../images/green-square.png',
      price: 20.99,
      countInStock: 10,
      brand: 'avo tree',
      rating: 4.5,
      numReviews: 29,
      description: 'high quality',
    },
    {
      _id: '2',
      name: 'Mustard Dad Hat',
      category: 'dad hats',
      image1: '../images/PSAVOMSTD19.jpg',
      image2: '../images/mustard-square.png',
      price: 20.99,
      countInStock: 20,
      brand: 'avo tree',
      rating: 5,
      numReviews: 54,
      description: 'high quality',
    },
    {
      _id: '3',
      name: 'Navy Dad Hat',
      category: 'dad hats',
      image1: '../images/PSAVONVY19.jpg',
      image2: '../images/navy-square.png',
      price: 20.99,
      countInStock: 0,
      brand: 'avo tree',
      rating: 4,
      numReviews: 16,
      description: 'high quality',
    },
    {
      _id: '4',
      name: 'White Dad Hat',
      category: 'dad hats',
      image1: '../images/PSAVOWHT19.jpg',
      image2: '../images/white-square.png',
      price: 20.99,
      countInStock: 20,
      brand: 'avo tree',
      rating: 5,
      numReviews: 73,
      description: 'high quality',
    },
    {
      _id: '5',
      name: 'Black Dad Hat',
      category: 'dad hats',
      image1: '/images/PSAVOBLK19.jpg',
      image2: '/images/black-square.png',
      price: 20.99,
      countInStock: 50,
      brand: 'avo tree',
      rating: 5,
      numReviews: 42,
      description: 'high quality',
    },
  ],
}

export default data;